name: Compilar guía práctica
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compilar guía
        uses: xu-cheng/latex-action@v2
        with:
          root_file: guia.tex
          post_compile: "latexmk -c"
          latexmk_shell_escape: true
      - run: |
          mkdir build
          cp guia.pdf build/guia.pdf
      - name: Deployar guía 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: guia-pdf
          folder: build
